# Generated by Django 4.0.6 on 2022-07-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='activity_flag2',
            new_name='status',
        ),
    ]
