# Generated by Django 4.0.6 on 2022-07-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(),
        ),
    ]
