# Generated by Django 4.0.6 on 2022-07-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_pages_amount_alter_book_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birthdate',
            new_name='date_of_birth',
        ),
    ]
