# Generated by Django 4.0.6 on 2022-07-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_birthdate_author_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
