# Generated by Django 4.0.6 on 2022-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(related_name='posts', to='blog.author'),
        ),
    ]
